import type { UserList } from "../../types/userLists"

export const headers = [
 { id: 1, label: "Organization" },
  { id: 2, label: "Username" },
  { id: 3, label: "Email" },
  { id: 4, label: "Phone number" },
  { id: 5, label: "Date Joined" },
  { id: 6, label: "Status" },
  { id: 7, label: "" },
]

export const data: UserList[] = [
  {
BVN: "57453467923",
company: "Applica",
date_joined: "2020-04-20T00:14:23.050Z",
duration: 2,
education: "OND",
email: "goodman@gmail.com",
employment: "Student",
facebook: "Goodman Villarreal",
gender: "Female",
guarantors: [{name: "French Howard", email: "@gmail.com", phone: "090753555656", relationship: "Relative"},],
id: "1",
instagram: "@goodman_villarreal",
marital_status: "Married",
monthly_income: "200,000 - 300,000",
name: "Goodman Villarreal",
office_email: "goodman@applica",
phone: "07065446432",
repayment: "50,000",
residence: "Hostel",
sector: "FinTech",
status: "Inactive",
twitter: "@goodman_villarreal",
username: "Goodman",
  },
  {
BVN: "57453467923",
company: "Leo",
date_joined: "2020-04-20T00:14:23.050Z",
duration: 2,
education: "OND",
email: "goodman@gmail.com",
employment: "Student",
facebook: "Goodman Villarreal",
gender: "Female",
guarantors: [{name: "French Howard", email: "@gmail.com", phone: "090753555656", relationship: "Relative"},],
id: "2",
instagram: "@goodman_villarreal",
marital_status: "Married",
monthly_income: "200,000 - 300,000",
name: "Goodman Villarreal",
office_email: "goodman@applica",
phone: "07065446432",
repayment: "50,000",
residence: "Hostel",
sector: "FinTech",
status: "Pending",
twitter: "@goodman_villarreal",
username: "Goodman",
  },
  {
BVN: "57453467923",
company: "Shade",
date_joined: "2020-04-20T00:14:23.050Z",
duration: 2,
education: "OND",
email: "goodman@gmail.com",
employment: "Student",
facebook: "Goodman Villarreal",
gender: "Female",
guarantors: [{name: "French Howard", email: "@gmail.com", phone: "090753555656", relationship: "Relative"},],
id: "3",
instagram: "@goodman_villarreal",
marital_status: "Married",
monthly_income: "200,000 - 300,000",
name: "Goodman Villarreal",
office_email: "goodman@applica",
phone: "07065446432",
repayment: "50,000",
residence: "Hostel",
sector: "FinTech",
status: "Blacklisted",
twitter: "@goodman_villarreal",
username: "Goodman",
  },
  {
BVN: "57453467923",
company: "Cain",
date_joined: "2020-04-20T00:14:23.050Z",
duration: 2,
education: "OND",
email: "goodman@gmail.com",
employment: "Student",
facebook: "Goodman Villarreal",
gender: "Female",
guarantors: [{name: "French Howard", email: "@gmail.com", phone: "090753555656", relationship: "Relative"},],
id: "4",
instagram: "@goodman_villarreal",
marital_status: "Married",
monthly_income: "200,000 - 300,000",
name: "Goodman Villarreal",
office_email: "goodman@applica",
phone: "07065446432",
repayment: "50,000",
residence: "Hostel",
sector: "FinTech",
status: "Active",
twitter: "@goodman_villarreal",
username: "Goodman",
  },
  {
BVN: "57453467923",
company: "Rose",
date_joined: "2020-04-20T00:14:23.050Z",
duration: 2,
education: "OND",
email: "goodman@gmail.com",
employment: "Student",
facebook: "Goodman Villarreal",
gender: "Female",
guarantors: [{name: "French Howard", email: "@gmail.com", phone: "090753555656", relationship: "Relative"},],
id: "5",
instagram: "@goodman_villarreal",
marital_status: "Married",
monthly_income: "200,000 - 300,000",
name: "Goodman Villarreal",
office_email: "goodman@applica",
phone: "07065446432",
repayment: "50,000",
residence: "Hostel",
sector: "FinTech",
status: "Pending",
twitter: "@goodman_villarreal",
username: "Goodman",
  },
 
 

]